### ISSUE TITLE
Articles in menu - sort by title?

### ISSUE THREAD

**Issue by kirschbombe** [kirschbombe/literaryparis#3]

**Comment by ghost** [comment]
The article submenu code has been updated to list article titles in alphabetical order, and the update pushed to the gh-pages branch.

The JS function [String.localeCompare](https://developer.mozilla.org/en-US/docs/Web/JavaScript/Reference/Global_Objects/String/localeCompare) is used for determining the sort order of the titles, with default (unconfigured) behavior.

The XSL file which turns an article into its menu title (app/script/xsl/article-menu.xsl) was updated to add a @sort-key attribute to the menu list:

```
        <li data-sort-key="...">
            <a href="...">...</a>
        </li>
```

and the JS code that assembles the menu (/app/js/views/menu.js) items handles the sort according to the @data-sort-key attribute, if available, and otherwise the text of the title (string content of the <a/> element).
